<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Message to The Obvious Foundation</title>
    <link href="http://fonts.googleapis.com/css?family=Amaranth:400,700" rel="stylesheet" type="text/css">
    <script src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
    <script src="http://documentcloud.github.com/underscore/underscore.js"></script>
    <script src="http://documentcloud.github.com/backbone/backbone.js"></script>
    <link href="style/default.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div id="container">
      <h1>A special message to The Obvious Foundation</h1>

      <p>
        Let me just go ahead and say that I love my current position, and employer.  Frankly, they do not really give me any reason to leave.  Nonetheless, I wouldn’t say that the technology I create helps people on a personal and social level (ex, twitter, blogger, or other collaborative web systems), though, it definitely does help them make money.  However, is that really the ONLY type of technology that I want to keep creating? Do my projects have to exist solely for the enjoyment of a very few privileged individuals? I’m not quite sure.
        However, in working with the Nerd of the Year, the failed astrophysicist, and Evan (no meat? Really? See my postscript below) I hope to create technology whose success is directly proportional to the positive impact it has, and, if I may kindly steal from your website, technology that makes people happy.  That’s probably my biggest motivation.
        All right, I concede.  The technology should definitely be financially rewarding.

        PS.  So, I once spent a month in a monastery in Southern California.  It was during a fast.  The monks ate only vegetables.  I adapted for as long as I could, but had to escape the second week to the nearest town for a burger (or two).  Can’t really blame me -the monastery didn’t have tofu.  If I join your team, I’ll try vegetarianism for a full month.
      </p>
      <section id="content">
      </section>
    </div>
  </body>
  <script type="text/javascript">
    $(function() {

      
    })
  </script>
</html>
